// Code generated by MockGen. DO NOT EDIT.
// Source: usecase/sso/interface.go

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/mernat/sso-clean-arch/models"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// AuthService mocks base method.
func (m *MockService) AuthService(user *models.User) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AuthService", user)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AuthService indicates an expected call of AuthService.
func (mr *MockServiceMockRecorder) AuthService(user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AuthService", reflect.TypeOf((*MockService)(nil).AuthService), user)
}

// RegistrationService mocks base method.
func (m *MockService) RegistrationService(user *models.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegistrationService", user)
	ret0, _ := ret[0].(error)
	return ret0
}

// RegistrationService indicates an expected call of RegistrationService.
func (mr *MockServiceMockRecorder) RegistrationService(user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegistrationService", reflect.TypeOf((*MockService)(nil).RegistrationService), user)
}
